### ISSUE TITLE
Stuck on standard and outdated

### ISSUE THREAD

**Issue by plushrib** [rufoa/ableton#4]

**Comment by rufoa** [comment]
Which version of Live are you using?

**Comment by rufoa** [comment]
Works correctly on the most recent version

![SCR-20241101-dbwi](https://github.com/user-attachments/assets/6640b892-9a16-41d3-9b18-795bc4146c72)

![SCR-20241101-dbua](https://github.com/user-attachments/assets/a1ecf1a4-4c59-4347-91bd-20ca43e60aeb)
